# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("accessibility.browsewithcaret_shortcut.enabled", false);
user_pref("app.update.auto", false);
user_pref("app.update.enabled", false);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1385391829);
user_pref("app.update.lastUpdateTime.background-update-timer", 0);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1385391949);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1385391709);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.disk.smart_size_cached_value", 358400);
user_pref("browser.chromeURL", "chrome://seb/content/seb.xul");
user_pref("browser.dom.window.dump.enabled", true);
user_pref("browser.download.manager.retention", 0);
user_pref("browser.download.manager.useWindow", false);
user_pref("browser.link.open_newwindow", 2);
user_pref("browser.startup.homepage_override.mstone", "ignore");
user_pref("browser.zoom.full", true);
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.lastAppVersion", "2.0");
user_pref("extensions.lastPlatformVersion", "13.0");
user_pref("extensions.shownSelectionUI", true);
user_pref("extensions.update.enabled", false);
user_pref("general.useragent.locale", "de-DE");
user_pref("general.useragent.override", "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:23.0) Gecko/20130730 seb/2.0 SEBKEY");
user_pref("gfx.direct3d.last_used_feature_level_idx", 0);
user_pref("javascript.options.showInConsole", true);
user_pref("javascript.options.strict", true);
user_pref("mousewheel.withaltkey.action", 3);
user_pref("mousewheel.withcontrolkey.action", 1);
user_pref("network.cookie.prefsMigrated", true);
user_pref("nglayout.debug.disable_xul_cache", true);
user_pref("nglayout.debug.disable_xul_fastload", true);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("privacy.popups.firstTime", false);
user_pref("privacy.popups.policy", 1);
user_pref("security.default_personal_cert", "Select Automatically");
user_pref("toolkit.defaultChromeURI", "chrome://seb/content/seb.xul");
user_pref("toolkit.singletonWindowType", "main");
user_pref("toolkit.telemetry.previousBuildID", "16062008");
