# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.auto", false);
user_pref("app.update.enabled", false);
user_pref("browser.chromeURL", "chrome://seb/content/seb.xul");
user_pref("browser.dom.window.dump.enabled", true);
user_pref("browser.download.manager.retention", 0);
user_pref("browser.download.manager.useWindow", false);
user_pref("browser.link.open_newwindow", 2);
user_pref("browser.startup.homepage_override.mstone", "ignore");
user_pref("extensions.update.enabled", false);
user_pref("javascript.options.showInConsole", true);
user_pref("javascript.options.strict", true);
user_pref("mousewheel.withaltkey.action", 3);
user_pref("nglayout.debug.disable_xul_cache", true);
user_pref("nglayout.debug.disable_xul_fastload", true);
user_pref("privacy.popups.firstTime", false);
user_pref("privacy.popups.policy", 1);
user_pref("toolkit.defaultChromeURI", "chrome://seb/content/seb.xul");
user_pref("toolkit.defaultChromeFeatures", "chrome,dialog=no,resizable=yes,scrollbars=yes");
user_pref("toolkit.singletonWindowType", "main");
