# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("accessibility.browsewithcaret_shortcut.enabled", false);
user_pref("app.update.auto", false);
user_pref("app.update.enabled", false);
user_pref("browser.chromeURL", "chrome://seb/content/seb.xul");
user_pref("browser.startup.homepage_override.mstone", "ignore");
user_pref("browser.dom.window.dump.enabled", true);
user_pref("browser.download.folderList", 2);
user_pref("browser.download.useDownloadDir", true);
user_pref("browser.download.manager.openDelay", 0);
user_pref("browser.download.manager.retention", 0);
user_pref("browser.download.manager.showAlertInterval", 0);
user_pref("browser.download.manager.showAlertOnComplete", true);
user_pref("browser.download.manager.showWhenStarting", false);
user_pref("browser.download.manager.useWindow", false);
user_pref("browser.helperApps.alwaysAsk.force", false);
user_pref("browser.link.open_newwindow", 2);
user_pref("browser.startup.homepage_override.mstone", "ignore");
user_pref("dom.ipc.plugins.flash.disable-protected-mode", true);
user_pref("extensions.update.enabled", false);
user_pref("javascript.options.showInConsole", true);
user_pref("javascript.options.strict", true);
user_pref("mousewheel.withaltkey.action", 3);
user_pref("mousewheel.withcontrolkey.action", 1);
user_pref("network.cookie.prefsMigrated", true);
user_pref("nglayout.debug.disable_xul_cache", true);
user_pref("nglayout.debug.disable_xul_fastload", true);
user_pref("privacy.popups.firstTime", false);
user_pref("privacy.popups.policy", 1);
user_pref("security.default_personal_cert", "Select Automatically");
user_pref("toolkit.defaultChromeURI", "chrome://seb/content/seb.xul");
user_pref("toolkit.defaultChromeFeatures", "chrome,dialog=no,resizable=yes,scrollbars=yes");
user_pref("toolkit.singletonWindowType", "main");
user_pref("full-screen-api.enabled", true);
user_pref("gfx.direct2d.disabled", false);
user_pref("layers.acceleration.disabled", false);
user_pref("browser.display.use_document_fonts", 1);
user_pref("network.http.spdy.enabled.http2", true);
