pref("app.update.auto", false);
pref("app.update.enabled", false);
pref("app.support.baseURL", "");
pref("toolkit.defaultChromeURI", "chrome://seb/content/seb.xul");
pref("toolkit.defaultChromeFeatures", "chrome,dialog=no,resizable=yes,scrollbars=yes");
pref("toolkit.singletonWindowType", "main");
pref("toolkit.telemetry.enabled", false);
pref("toolkit.telemetry.server", "");
pref("toolkit.telemetry.server_owner", "");
pref("experiments.manifest.uri", "");
pref("toolkit.telemetry.cachedClientID", "");
pref("toolkit.telemetry.archive.enabled", false);
pref("toolkit.telemetry.infoURL","");
pref("toolkit.telemetry.optoutSample",false);
pref("toolkit.telemetry.previousBuildID","");
pref("toolkit.telemetry.reportingpolicy.firstRun",false);
pref("toolkit.telemetry.unified",false);
pref("toolkit.telemetry.unifiedIsOptIn",false);
pref("accessibility.browsewithcaret_shortcut.enabled", false);
pref("browser.chromeURL", "chrome://seb/content/seb.xul");
pref("browser.startup.homepage_override.mstone", "ignore");
pref("browser.download.manager.retention", 0);
pref("browser.download.manager.useWindow", false);
pref("browser.link.open_newwindow", 2);
pref("browser.startup.homepage_override.mstone", "ignore");
pref("browser.zoom.full", true);
pref("extensions.update.enabled", false);
pref("mousewheel.withaltkey.action", 3);
pref("mousewheel.withcontrolkey.action", 1);
pref("network.cookie.prefsMigrated", true);
pref("privacy.popups.firstTime", false);
pref("privacy.popups.policy", 1);
pref("security.default_personal_cert", "Select Automatically");
pref("gecko.handlerService.allowRegisterFromDifferentHost", true);
pref("full-screen-api.enabled", true);
pref("gfx.direct2d.disabled", false);
pref("layers.acceleration.disabled", false);
pref("general.useragent.locale", "de-DE");
